package car

var (
	carMakers = []string{
		"Acura",
		"Alfa Romeo",
		"Audi",
		"Bentley",
		"BMW",
		"Buick",
		"Cadillac",
		"Chevrolet",
		"Chrysler",
		"Dodge",
		"Fiat",
		"Ford",
		"Genesis",
		"GMC",
		"Honda",
		"Hyundai",
		"Infiniti",
		"Jaguar",
		"Jeep",
		"Kia",
		"Land Rover",
		"Lexus",
		"Lincoln",
		"Maserati",
		"Mazda",
		"Mercedes-Benz",
		"Mini",
		"Mitsubishi",
		"Nissan",
		"Polestar",
		"Porsche",
		"Ram",
		"Saab",
		"Smart",
		"Subaru",
		"Tesla",
		"Toyota",
		"Volkswagen",
		"Volvo",
	}

	carModels = []string{
		"3 Series",
		"7 Series",
		"A7",
		"Acadia",
		"Accent",
		"Accord Hybrid",
		"Accord",
		"Blazer",
		"Bolt EV",
		"Camaro",
		"Charger",
		"Cherokee",
		"Civic",
		"Colorado Crew Cab",
		"Compass",
		"Corvette",
		"CR-V",
		"CT5",
		"CT6-V",
		"Durango",
		"E-PACE",
		"EcoSport",
		"Edge",
		"Elantra GT",
		"Elantra",
		"Enclave",
		"Encore",
		"Envision",
		"Equinox",
		"Escalade ESV",
		"Escalade",
		"Escape",
		"Expedition MAX",
		"Expedition",
		"Explorer",
		"F-PACE",
		"F150 SuperCrew Cab",
		"Fusion",
		"G70",
		"G80",
		"Gladiator",
		"Grand Cherokee",
		"HR-V",
		"I-PACE",
		"Impala",
		"Insight",
		"Ioniq Plug-in Hybrid",
		"Kona Electric",
		"Kona",
		"Malibu",
		"MDX",
		"Mustang",
		"NEXO",
		"Odyssey",
		"Pacifica",
		"Palisade",
		"Passport",
		"Q3",
		"Q5",
		"Q50",
		"Q60",
		"QX50",
		"QX60",
		"QX80",
		"R8",
		"Ranger SuperCab",
		"Ranger SuperCrew",
		"RDX",
		"Renegade",
		"Ridgeline",
		"RLX",
		"Santa Fe",
		"Sierra 1500 Crew Cab",
		"Sierra 2500 HD Crew Cab",
		"Sierra 3500 HD Crew Cab",
		"Silverado 1500 Crew Cab",
		"Silverado 2500 HD Crew Cab",
		"Silverado 3500 HD Crew Cab",
		"Sonata",
		"Spark",
		"SQ5",
		"Suburban",
		"Tahoe",
		"Terrain",
		"TLX",
		"Traverse",
		"Trax",
		"Tucson",
		"Veloster",
		"Venue", "Pilot",
		"Voyager",
		"X3",
		"X5",
		"X7",
		"XT4",
		"XT5",
		"XT6",
		"Yukon XL",
		"Yukon",
	}

	carCategories        = []string{"SUV", "Sedan", "Coupe", "Convertible", "Hatchback", "Pickup", "Van", "Minivan", "Wagon"}
	carFuelTypes         = []string{"Bio Gas", "Diesel", "Eletric", "Ethanol", "Hybrid", "Petrol"}
	carTransmissionGears = []string{"Automatic", "CVT", "Eletronic", "Manual", "Semi-auto", "Tiptronic"}
)
